# Generated by Django 2.2.9 on 2020-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200728_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
