# Generated by Django 2.2 on 2020-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200817_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте картинку здесь.', null=True, upload_to='posts/', verbose_name='Прикрепить картинку'),
        ),
    ]
